seed: 1

models:
  policy:
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    network:
      - layers: [256, 256, 256]
        activations: elu
  value:
    clip_actions: False

agent:
  rollouts: 256
  learning_epochs: 5
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 1.0e-04
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  random_timesteps: 512
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.02
  value_loss_scale: 1.0
  kl_threshold: 0.0
  time_limit_bootstrap: True
  experiment:
    directory: "drone_recon"
    experiment_name: ""
    write_interval: 1000
    checkpoint_interval: 0

trainer:
  timesteps: 25000
  environment_info: log
